FROM node:lts-bookworm AS dependencia
WORKDIR /
COPY package.json .
RUN npm install

FROM node:lts-alpine3.20 as deploy
WORKDIR /
COPY --from=dependencia ./node_modules ./node_modules
COPY . .
EXPOSE 3333
CMD [ "node" , "app.js" ]